version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
    depends_on:
      - server

  server:
    image: farenheim7/planit-dev-server:0.6
    container_name: planit-server
    restart: always
    # env_file:
    #   - .env.production
    ports:
      - '8000:8000'
    command: ['npm', 'start']

  dev-server:
    image: farenheim7/planit-dev-server
    container_name: planit-dev-server
    restart: always
    ports:
      - '8000:8000'
    command: ['npm', 'run', 'start:dev']

  npm:
    image: node:18.14
    working_dir: /server
    entrypoint: ['npm']
    volumes:
      - .:/server

  test-db:
    image: postgres:14.6
    container_name: 'planit-test'
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'planit-test'
