version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
    depends_on:
      - server

  server:
    build:
      context: .
      dockerfile: dockerfiles/api-server.dockerfile
    container_name: api-server
    restart: always
    env_file:
      - .env.production
    ports:
      - 8000:8000
    command: ['npm', 'start']

  dev-server:
    image: farenheim7/planit-dev-server
    container_name: planit-dev-server
    restart: always
    ports:
      - 8000:8000
    command: ['npm', 'run', 'start:dev']

  npm:
    image: node:18.14
    working_dir: /server
    entrypoint: ['npm']
    volumes:
      - ./src:/server
