name: Planit Server CI

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
      - name: Get Code from Repository
        uses: actions/checkout@v3

      - name: Use Node.js v.18.
        uses: actions/setup-node@v3
        with:
          node-version: '18.14.2'
